"""Therapeutic-area mapper shared by stratify.py, coverage.py and inference.py.

Priority-order keyword cascade over a trial's condition terms: the areas are
tried in the order of AREAS, and a trial goes to the first area in which one
of its condition terms contains a keyword. A keyword does not count for a term
that also contains one of its EXCEPT strings ('hypertension' is cardiovascular,
'ocular hypertension' is not).

The keywords were checked against the condition terms they capture among the
trials of the main window. The areas remain coarse, and a trial with
conditions in two areas is routed by list order, not by clinical judgment."""

AREAS = [
    (
        'Oncology',
        [
            'cancer',
            'carcinoma',
            'tumor',
            'tumour',
            'neoplas',
            'lymphoma',
            'leukemia',
            'leukaemia',
            'melanoma',
            'sarcoma',
            'myeloma',
            'glioma',
            'blastoma',
            'oncolog',
            'metasta',
            'malignan',
            'mesothelioma',
            'hodgkin',
            'myelofibrosis',
            'myelodysplas',
            'myeloproliferative',
            'thrombocythemia',
            'polycythemia vera',
            'mycosis fungoides',
            'nsclc',
        ],
    ),
    (
        'Infectious/Vaccine',
        [
            'hiv',
            'hepatitis',
            'influenza',
            'covid',
            'sars-cov',
            'infection',
            'bacterial',
            'bacteremia',
            'bacteraemia',
            'viral',
            'virus',
            'tuberculosis',
            'malaria',
            'sepsis',
            'septic',
            'vaccin',
            'immunisation',
            'immunization',
            'pneumonia',
            'antibiotic',
            'antiviral',
            'pneumococc',
            'meningococc',
            'herpes',
            'varicella',
            'dengue',
            'chikungunya',
            'polio',
            'measles',
            'pertussis',
            'diphtheria',
            'tetanus',
            'cholera',
            'typhoid',
            'rabies',
            'gonorrh',
            'chlamydia',
            'syphilis',
            'candidiasis',
            'mycosis',
            'fungal',
            'tinea',
            'scabies',
            'head lice',
            'molluscum',
            'common cold',
            'cellulitis',
            'impetigo',
            'otitis media',
        ],
    ),
    (
        'Cardiometabolic',
        [
            'diabet',
            'obesity',
            'overweight',
            'cardiovascular',
            'cardiac',
            'cardiomyopath',
            'heart failure',
            'heart disease',
            'coronary',
            'hypertension',
            'cholesterol',
            'lipid',
            'triglycerid',
            'atrial fibrillation',
            'tachycardia',
            'arrhythm',
            'myocardial',
            'stroke',
            'metabolic syndrome',
            'nash',
            'steatohepatitis',
            'fatty liver',
            'thrombosis',
            'thromboembol',
            'embolism',
            'angina',
            'atherosclero',
            'peripheral arter',
            'aortic',
        ],
    ),
    (
        'Neuro/Psych',
        [
            'alzheimer',
            'parkinson',
            'dementia',
            'depress',
            'schizophren',
            'epilep',
            'migraine',
            'multiple sclerosis',
            'amyotrophic',
            'neuropath',
            'psychiatr',
            'anxiety',
            'bipolar',
            'chronic pain',
            'seizure',
            'huntington',
            'neurodegener',
            'adhd',
            'attention deficit',
            'autism',
            'ptsd',
            'traumatic stress',
            'obsessive',
            'insomnia',
            'narcolepsy',
            'tourette',
            'opioid use disorder',
            'opioid-use disorder',
            'opioid-related',
            'opioid withdrawal',
            'opioid dependence',
            'alcohol use',
            'alcohol dependence',
            'smoking cessation',
            'tobacco use',
            'myasthenia',
            'muscular dystrophy',
            'spinal muscular atrophy',
            'multiple system atrophy',
            'neuromyelitis',
            'rett syndrome',
            'dravet',
            'lennox',
            'infantile spasms',
            'restless legs',
            'essential tremor',
            'tardive',
            'traumatic brain',
            'cerebral palsy',
            'delirium',
        ],
    ),
    (
        'Immunology/Inflammation',
        [
            'arthritis',
            'spondylitis',
            'psoriasis',
            'crohn',
            'colitis',
            'lupus',
            'inflammat',
            'asthma',
            'copd',
            'chronic obstructive pulmonary',
            'dermatitis',
            'eczema',
            'atopic',
            'ankylosing',
            'immune',
            'immunodeficien',
            'autoimmun',
            'ulcerative',
            'urticaria',
            'allerg',
            'eosinophilic',
            'nasal polyp',
            'rhinosinusitis',
            'hidradenitis',
            'alopecia areata',
            'vitiligo',
            'pemphig',
            'prurigo',
            'uveitis',
            'myositis',
            'arteritis',
            'vasculitis',
            'scleroderma',
            'systemic sclerosis',
            'sarcoidosis',
            'sjogren',
            'graft versus host',
            'graft-versus-host',
            'gvhd',
        ],
    ),
]

# keyword -> strings that cancel it when they occur in the same condition term
EXCEPT = {
    'hepatitis': ['steatohepatitis'],  # NASH is metabolic, not an infection
    'hypertension': ['ocular', 'intracranial', 'portal'],  # eye, brain, liver
    'diabet': ['macular', 'retinopath'],  # eye disease
    'stroke': ['heat stroke'],
    'depress': ['respiratory depression'],
    'arthritis': ['osteoarthritis'],  # degenerative, not immune-mediated
    'colitis': ['enterocolitis'],
    'inflammat': ['ocular', 'eye', 'cataract', 'gingival', 'pelvic'],
    'cardiac': ['non-cardiac', 'noncardiac'],
    'fungal': ['allergic fungal'],  # a hypersensitivity, not an infection
    'sjogren': ['larsson'],  # Sjogren-Larsson syndrome is a genetic disorder
}


def _matches(keyword, term):
    return keyword in term and not any(
        x in term for x in EXCEPT.get(keyword, ())
    )


def area_of(cond, nct):
    terms = [t.lower() for t in cond.get(nct, [])]
    if not terms:
        return 'Unknown/other'
    for name, kws in AREAS:
        if any(_matches(k, t) for t in terms for k in kws):
            return name
    return 'Other/rare'
