"""Merge the recorded numbers into paper/numbers.tex and into the README.

Reads numbers/*.json (one file per analysis script) and writes:

  numbers.tex  one definition per number, read by the manuscript and the
               supplement as \\num{name}; an unknown name stops the build.
               It also defines \\tablebody{name}, which reads tables/name.tex
               from the folder the documents are built in (paper/)
  README.md    the block between the two 'findings' markers, rendered from
               readme_findings.md, whose {{name}} placeholders are numbers

Run after the analysis scripts.
"""

import re

from paper_numbers import read_numbers
from repo_files import PAPER, read_text, write_text

HEADER = r"""% Generated by write_numbers.py from numbers/*.json. Do not edit.
\makeatletter
\newcommand{\num}[1]{%
  \@ifundefined{num@#1}{\errmessage{Unknown number: #1}}{\@nameuse{num@#1}}}
% rows of a generated table; the primitive \input works inside a tabular
\newcommand{\tablebody}[1]{\@@input tables/#1.tex }
"""
START, END = '<!-- findings:start -->', '<!-- findings:end -->'


def main():
    numbers = read_numbers()
    lines = [
        f'\\@namedef{{num@{name}}}{{{entry["tex"]}}}'
        for name, entry in sorted(numbers.items())
    ]
    write_text(
        HEADER + '\n'.join(lines) + '\n\\makeatother\n', PAPER + 'numbers.tex'
    )

    def fill(match):
        return numbers[match.group(1)]['txt']

    findings = re.sub(
        r'\{\{([A-Za-z0-9.]+)\}\}',
        fill,
        read_text(PAPER + 'readme_findings.md'),
    )
    readme = read_text('README.md')
    before, rest = readme.split(START)
    _, after = rest.split(END)
    write_text(
        f'{before}{START}\n{findings.strip()}\n{END}{after}', 'README.md'
    )
    print(f'numbers.tex: {len(numbers)} numbers; README findings refreshed')


if __name__ == '__main__':
    main()
